version: "3.9"
services:
    db:
        image: mysql:latest
        container_name: db6_openclassrooms
        restart: always
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: tomtroc
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        ports:
            - "3308:3306"
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php6_openclassrooms
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma6_openclassrooms
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ""
        depends_on:
            - db

volumes:
    mysql:
